<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RollForward>Major</RollForward>
    <LangVersion>12.0</LangVersion>
    <UseAppHost>false</UseAppHost>
    <Deterministic>true</Deterministic>
    <UseSharedCompilation>false</UseSharedCompilation>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ShaderHitchPipeline.Core/ShaderHitchPipeline.Core.csproj" />
  </ItemGroup>
</Project>
